### ISSUE TITLE
HTTPRequest instance

### ISSUE THREAD

**Issue by beMang** [beMang/News#1]
Voici l'erreur : 

> Fatal error: Uncaught Error: Class 'news\HTTPRequest' not found in C:\Users\adrie\Desktop\Jeux\Site\StudioTheadri Site\vendor\bemang\news\news\ActuControleur.php:10 Stack trace: #0 C:\Users\adrie\Desktop\Jeux\Site\StudioTheadri Site\App\FrontEnd\View\news.php(6): news\ActuControleur->__construct(Object(adriLib\HTTPRequest)) #1 C:\Users\adrie\Desktop\Jeux\Site\StudioTheadri Site\App\FrontEnd\app.php(13): require('C:\\Users\\adrie\\...') #2 C:\Users\adrie\Desktop\Jeux\Site\StudioTheadri Site\index.php(2): require('C:\\Users\\adrie\\...') #3 {main} thrown in C:\Users\adrie\Desktop\Jeux\Site\StudioTheadri Site\vendor\bemang\news\news\ActuControleur.php on line 10

HTTPRequest doit être instancié comme ceci : new adrilib\HTTPRequest(); pour être valide dans ActuControleur.php.

beMang

**Comment by beMang** [comment]
Ce sera corrigé dans le prochain commit.

Ce sera appelé comme ceci : Application::H$HTTPRequest

Il n'y aura plus de constructeur.
